### ISSUE TITLE
HPO could be enabled by a HPO configuration file(yaml or json) instead of adding code explicitly in example.py

### ISSUE THREAD

**Issue by sywangyi** [huggingface/transformers#18384]
### Feature request

now, the HPO should be enabled by adding some code in example.py(like run_glue.py) to indicate the HPO backend, metric, hp space. code like
```
     def glue_hp_space(trial):
          return [
               {"bounds": {"min": 1e-6, "max": 1e-4}, "name": "learning_rate", "type": "double"},
               {
                   "categorical_values": ["16", "32", "64", "128"],
                   "name": "per_device_train_batch_size",
                   "type": "categorical",
               },
           ]
    def model_init(trial):
            return AutoModelForSequenceClassification.from_pretrained(
                model_args.model_name_or_path,
                from_tf=bool(".ckpt" in model_args.model_name_or_path),
                config=config,
                cache_dir=model_args.cache_dir,
                revision=model_args.model_revision,
                use_auth_token=True if model_args.use_auth_token else None,
            )

        # Initialize our Trainer
       trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            compute_metrics=compute_metrics,
            model_init=model_init,
            tokenizer=tokenizer,
            data_collator=data_collator,
        )
        best_trial = trainer.hyperparameter_search(
            direction="maximize", backend="sigopt", hp_space=glue_hp_space, n_trials=2
        )
```
could we add a configuration file and pass it as an argument to trainer for the easy usage of the HPO?
yaml could like 
```
HPO.yaml

name: hg_glue_optimization
backend:  sigopt
metrics:
 -name: accuracy
  strategy: optimize
  objective: maximize
parameters:
 -name: learning_rate
   bounds:
      min: 1e-6
      max: 1e-4
   type: double
 -name: per_device_train_batch_size
   categorical_values:
      - 16
      - 32
      - 64
      - 128
    type: categorical_values
trials: 10

```
training_args could be responsible for the yaml parse and convert to input space format according to the different backend (Optuna, Sigopt, Wandb...)

### Motivation

I am always frustrated when I need to modify the example code to enable HPO, and change it according to the different HPO backend

### Your contribution

I could help submit PR after all are aligned on this point
