### ISSUE TITLE
Saving LLAMA 13B checkpoint with FSDP finetuning results in disk full error

### ISSUE THREAD

**Issue by ari9dam** [huggingface/transformers#24766]
### System Info

transformers - installed from source
accelerate - installed from source
torch 2.0.1

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Finetune LLAMA 13B with accelerate launcher. Saving strategy "epoch". FSDP based training.

### Expected behavior

I would be able to save the checkpoint. Now getting disk full error. Note that the disk initially had space. My code was working with transformers-4.28, accelerate 0.18 and torch 1.13. This error started after I moved to accelerate based launcher and upgraded the packages.

**Comment by ari9dam** [comment]
It seems saving a checkpoint requires more than 213GB (My hard size). Not sure if it is intended.

**Comment by amyeroberts** [comment]
Hi @ari9dam, thanks for raising this issue. 

Could you a minimal code snippet we can use to reproduce the error? Specifically how accelerate launcher is being used, training arguments, and FDSP config. 

For the transformers and accelerate source installs, which commit are you running from? 

When you say saving a checkpoint - am I right in saying this is the memory requirement for saving a single checkpoint after 1 epoch of training is > 213 GB?

**Comment by ari9dam** [comment]
Yes, " the memory requirement for saving a single checkpoint after 1 epoch of training is > 213 GB?". 

`accelerate launch --config_file accelerate_config.yaml --num_machines 4 --num_processes 16 --machine_rank $NODE_RANK --main_process_ip $MASTER_ADDR --main_process_port $MASTER_PORT ./trainer.py --model_name_or_path ".." --data_path "..." --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --do_train --evaluation_strategy no --output_dir outputs --learning_rate 2e-5 --num_train_epochs 4 --lr_scheduler_type cosine --warmup_ratio 0.03 --weight_decay 0.0 --logging_steps 1 --save_strategy epoch --bf16 true --tf32 true --load_best_model_at_end false --model_max_length 1024 --gradient_checkpointing true --save_total_limit 1 --model_resume_from_checkpoint false --torch_compile false`

### accelerate_config.yaml
```
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_use_orig_params: true
main_training_function: main
num_machines: 1
num_processes: 2
mixed_precision: bf16
rdzv_backend: static
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
transformers==4.31.0.dev0 (https://github.com/huggingface/transformers/commit/45025d92f815675e483f32812caa28cce3a960e7)
 accelerate==0.21.0.dev0 (https://github.com/huggingface/accelerate/commit/7954a28a71d484c4182a6b1074c1b8cc51642fc9)
