### ISSUE TITLE
Docker container with development environment for Transformers library

### ISSUE THREAD

**Issue by manuelsh** [huggingface/transformers#32628]
### Feature request

A docker container that one can use with or without GPU that has everything to start developing, if it doesn't exist and a reference to it in the `CONTRIBUTING.MD` file.

### Motivation

Reduce the barrier to start developing in any system with docker.

### Your contribution

I could build it. Would be something in the lines of:

```
FROM python:3.10

# Install system dependencies
RUN apt-get update && \
    apt-get install -y git && \
    pip install --upgrade pip --no-cache-dir && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set a temp directory to install environment
WORKDIR /usr/src/temp

# Clone the repository
RUN git clone https://github.com/huggingface/transformers.git

# Set the working directory to the cloned repository
WORKDIR /usr/src/temp/transformers

# Install development dependencies 
RUN pip install -e .[dev]

# Go tot he working directory for development
WORKDIR /usr/src/app

```

plus a docker compose like:

```
services:
  app:
    build: .
    volumes:
      - ~:/usr/src/app
    ports:
      - "8000:8000"
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - RUN_SLOW=true
```
